/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Loyalty Cards API
 * The loyalty cards API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Card,
  CreateCardDto,
  UpdateCardDto
} from '../../model';





export const cardsControllerCreate = (
    createCardDto: CreateCardDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Card>> => {
    
    
    return axios.default.post(
      `/cards`,
      createCardDto,options
    );
  }



export const getCardsControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardsControllerCreate>>, TError,{data: CreateCardDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof cardsControllerCreate>>, TError,{data: CreateCardDto}, TContext> => {

const mutationKey = ['cardsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardsControllerCreate>>, {data: CreateCardDto}> = (props) => {
          const {data} = props ?? {};

          return  cardsControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CardsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof cardsControllerCreate>>>
    export type CardsControllerCreateMutationBody = CreateCardDto
    export type CardsControllerCreateMutationError = AxiosError<unknown>

    export const useCardsControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardsControllerCreate>>, TError,{data: CreateCardDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardsControllerCreate>>,
        TError,
        {data: CreateCardDto},
        TContext
      > => {

      const mutationOptions = getCardsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const cardsControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Card[]>> => {
    
    
    return axios.default.get(
      `/cards`,options
    );
  }




export const getCardsControllerFindAllQueryKey = () => {
    return [
    `/cards`
    ] as const;
    }

    
export const getCardsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof cardsControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardsControllerFindAll>>> = ({ signal }) => cardsControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof cardsControllerFindAll>>>
export type CardsControllerFindAllQueryError = AxiosError<unknown>


export function useCardsControllerFindAll<TData = Awaited<ReturnType<typeof cardsControllerFindAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof cardsControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardsControllerFindAll<TData = Awaited<ReturnType<typeof cardsControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof cardsControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardsControllerFindAll<TData = Awaited<ReturnType<typeof cardsControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCardsControllerFindAll<TData = Awaited<ReturnType<typeof cardsControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const cardsControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Card>> => {
    
    
    return axios.default.get(
      `/cards/${id}`,options
    );
  }




export const getCardsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/cards/${id}`
    ] as const;
    }

    
export const getCardsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof cardsControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardsControllerFindOne>>> = ({ signal }) => cardsControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof cardsControllerFindOne>>>
export type CardsControllerFindOneQueryError = AxiosError<unknown>


export function useCardsControllerFindOne<TData = Awaited<ReturnType<typeof cardsControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof cardsControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardsControllerFindOne<TData = Awaited<ReturnType<typeof cardsControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof cardsControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardsControllerFindOne<TData = Awaited<ReturnType<typeof cardsControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCardsControllerFindOne<TData = Awaited<ReturnType<typeof cardsControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardsControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const cardsControllerUpdate = (
    id: string,
    updateCardDto: UpdateCardDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/cards/${id}`,
      updateCardDto,options
    );
  }



export const getCardsControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardsControllerUpdate>>, TError,{id: string;data: UpdateCardDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof cardsControllerUpdate>>, TError,{id: string;data: UpdateCardDto}, TContext> => {

const mutationKey = ['cardsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardsControllerUpdate>>, {id: string;data: UpdateCardDto}> = (props) => {
          const {id,data} = props ?? {};

          return  cardsControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CardsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof cardsControllerUpdate>>>
    export type CardsControllerUpdateMutationBody = UpdateCardDto
    export type CardsControllerUpdateMutationError = AxiosError<unknown>

    export const useCardsControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardsControllerUpdate>>, TError,{id: string;data: UpdateCardDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardsControllerUpdate>>,
        TError,
        {id: string;data: UpdateCardDto},
        TContext
      > => {

      const mutationOptions = getCardsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const cardsControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/cards/${id}`,options
    );
  }



export const getCardsControllerRemoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof cardsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['cardsControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  cardsControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CardsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof cardsControllerRemove>>>
    
    export type CardsControllerRemoveMutationError = AxiosError<unknown>

    export const useCardsControllerRemove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCardsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    