/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Loyalty Cards API
 * The loyalty cards API description
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Card
} from '../../model';


export const getCardsControllerCreateResponseMock = (overrideResponse: Partial< Card > = {}): Card => ({id: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), businessName: faker.string.alpha({length: {min: 10, max: 20}}), points: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), targetPoints: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), color: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getCardsControllerFindAllResponseMock = (): Card[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), businessName: faker.string.alpha({length: {min: 10, max: 20}}), points: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), targetPoints: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), color: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getCardsControllerFindOneResponseMock = (overrideResponse: Partial< Card > = {}): Card => ({id: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), businessName: faker.string.alpha({length: {min: 10, max: 20}}), points: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), targetPoints: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), color: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getCardsControllerCreateMockHandler = (overrideResponse?: Card | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Card> | Card), options?: RequestHandlerOptions) => {
  return http.post('*/cards', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCardsControllerCreateResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCardsControllerFindAllMockHandler = (overrideResponse?: Card[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Card[]> | Card[]), options?: RequestHandlerOptions) => {
  return http.get('*/cards', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCardsControllerFindAllResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCardsControllerFindOneMockHandler = (overrideResponse?: Card | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Card> | Card), options?: RequestHandlerOptions) => {
  return http.get('*/cards/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCardsControllerFindOneResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCardsControllerUpdateMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/cards/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getCardsControllerRemoveMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/cards/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getCardsMock = () => [
  getCardsControllerCreateMockHandler(),
  getCardsControllerFindAllMockHandler(),
  getCardsControllerFindOneMockHandler(),
  getCardsControllerUpdateMockHandler(),
  getCardsControllerRemoveMockHandler()
]
