/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Loyalty Cards API
 * The loyalty cards API description
 * OpenAPI spec version: 1.0
 */

export interface Card {
  id: number;
  businessName: string;
  points: number;
  targetPoints: number;
  color: string;
  createdAt: string;
  updatedAt: string;
}
