/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Loyalty Cards API
 * The loyalty cards API description
 * OpenAPI spec version: 1.0
 */

export interface CreateCardDto {
  businessName: string;
  targetPoints: number;
  points?: number;
  color?: string;
}
